baseurl = "http://cosyman.github.io/"
#baseurl = "http://localhost:1313/"

title = "兰天"

languageCode = "zh-cn"
disqusShortname = "cosyman" # Optional, enable Disqus integration
metaDataFormat = "toml"

theme = "hyde-y"


paginate = 10
paginatePath = "page"

[author]
    name = "兰天"
    email = "cosman@outlook.com"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    tag = "keywords"
    topic = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # Used when a given page doesn't set its own.
    defaultKeywords = "cosyman,bluesky,兰天"

    sidebar = "left"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "Home"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    # Metadata used to drive integrations.
    googleAuthorship = "remotejavasky"
    googleAnalytics = "UA-64429204-1"
    gravatarHash = "29bea2982cf098795915166d7a907376"

    # Sidebar social links, these must be full URLs.
    github = "cosyman"
    linkedin = "blueskyyao"
    #googleplus = "106762087260771841123"
    facebook = ""
    twitter = "bluesky_yao"

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []
